#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';
use App\Kernel;
use Symfony\Component\Console\Application;
use AppBundle\CronCommand\CronCommand as CronCommand;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Dotenv\Dotenv;
// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read https://symfony.com/doc/current/setup.html#checking-symfony-application-configuration-and-setup
// for more information
//umask(0000);

$application = new Application();
$application->add(new CronCommand);
$application->run();
